name: 'documentation'
description: 'A Library for create documentation super easy and fast customizable'
version: '0.0.2'
publish_to: 'none'
environment: 
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  cupertino_icons: '^1.0.6'
  path: '^1.9.0'
  general_lib: '^0.0.43'
  general_lib_flutter: '^0.0.24'
  markdown_flutter: '^0.0.7'
  markdown_widget: '^2.3.2+2'
  carousel_slider: '^4.2.1'
  easy_rich_text: '^2.1.0'
  icons_plus: '^5.0.0'
  flutter_hicons: '^0.1.0'
  url_launcher: '^6.2.6'
  cool_alert: '^2.0.1'
  general_lib_assets_flutter: 
    path: '/home/galaxeus/.pub-cache/hosted/pub.dev/general_lib_assets_flutter-0.0.0'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^3.0.0'
flutter: 
  uses-material-design: true
  assets: 
    - 'assets/logo/telegram.png'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
repository: 'https://github.com/azkadev/documentation'
homepage: 'https://github.com/azkadev/documentation'
issue_tracker: 'https://github.com/azkadev/documentation/issues'
documentation: 'https://github.com/azkadev/documentation/tree/main/docs'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
