name: 'documentation_project'
description: 'A Library for create documentation super easy and fast customizable'
version: '0.0.2'
repository: 'https://github.com/azkadev/documentation'
homepage: 'https://github.com/azkadev/documentation'
issue_tracker: 'https://github.com/azkadev/documentation/issues'
documentation: 'https://github.com/azkadev/documentation/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  general_lib: '^0.0.36'
  mason_logger: '^0.2.11'
  packagex: '^0.0.58'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
dependency_overrides: 
  pointycastle: '3.8.0'
